[workspace]
resolver = "2"
members = [
    "devolve-ui-core",
    "devolve-ui-macros",
    "dui-basic",
    "mini-rx",
    "zmq2",
    "dyn_struct",
    "typed-arena-any-vec",
    "winit-modular"
]
default-members = [
    "devolve-ui-core",
    "devolve-ui-macros",
    "dui-basic",
    "mini-rx",
    "zmq2",
    "dyn_struct",
    "typed-arena-any-vec",
    "winit-modular"
]
