[workspace]
members = [
    "devolve-ui",
    "devolve-ui-derive",
    "devolve-ui-forms",
    "mini-rx"
]
default-members = [
    "devolve-ui",
    "devolve-ui-derive",
    "devolve-ui-forms",
    "mini-rx"
]
