[workspace]
resolver = "2"
members = [
    "devolve-ui-core",
    "devolve-ui-macros",
    "mini-rx",
    "zmq2",
    "dyn_struct",
]
default-members = [
    "devolve-ui-core",
    "devolve-ui-macros",
    "mini-rx",
    "zmq2",
    "dyn_struct"
]
