[workspace]
members = [
    "devolve-ui",
    "devolve-ui-derive",
    "devolve-ui-prompt",
    "devolve-ui-tui",
    "devolve-ui-tui-forms",
    "mini-rx",
    "dyn_struct"
]
default-members = [
    "devolve-ui",
    "devolve-ui-derive",
    "devolve-ui-prompt",
    "devolve-ui-tui",
    "devolve-ui-tui-forms",
    "mini-rx",
    "dyn_struct"
]
