[package]
name = "devolve-ui"
version = "0.1.0"
authors = ["jakobeha"]
description = "TUI (and planned future GUI) library using Reactive programming"
repository = "https://github.com/jakobeha/devolve-ui.rs"
license = "Apache-2.0"
keywords = ["ui", "tui", "terminal"]
categories = ["command-line-interface", "gui"]
edition = "2021"

[lib]
# lib for normal, cdylib for wasm
crate-type = ["lib", "cdylib"]

[features]
# Include debug features by default
default = ["obs-ref", "input", "time", "time-blocking", "debug"]
obs-ref = ["smallvec"]
time = ["tokio"]
time-blocking = ["time", "tokio/rt"]
input = ["bitflags"]
logging = ["serde", "arrayvec/serde", "serde_json", "chrono"]
tui = ["color", "libc", "crossterm", "lazy_static", "unicode-width"]
tui-images = ["tui", "semver", "tempfile", "sixel", "sixel-sys", "png", "base64", "devolve-ui-forms/tui-images"]
color = ["palette"]
debug = ["bitflags"]
wasm = ["wasm-bindgen", "js-sys"]

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples=examples"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
devolve-ui-derive = { path = "../devolve-ui-derive" }
derivative = "2.2.0"
arrayvec = "0.7.2"
replace_with = "0.1.7"
derive_more = "0.99.17"
log = "0.4.17"
stable_deref_trait = "1.2.0"
palette = { version = "0.6.0", optional = true }
smallvec = { version = "1.8.0", optional = true }
tokio = { version = "1.18.2", features = ["time"], optional = true }
bitflags = { version = "1.3.2", optional = true }
libc = { version = "0.2.126", optional = true }
crossterm = { version = "0.23.2", optional = true }
backtrace = { version = "0.3.65", optional = true }
serde = { version = "1.0.137", features = ["derive"], optional = true }
serde_json = { version = "1.0.81", optional = true }
chrono = { version = "0.4.19", features = ["serde"], optional = true }
lazy_static = { version = "1.4.0", optional = true }
unicode-width = { version = "0.1.9", optional = true }
semver = { version = "1.0.9", optional = true }
sixel = { version = "0.3.2", optional = true }
sixel-sys = { version = "0.3.1", optional = true }
tempfile = { version = "3.3.0", optional = true }
png = { version = "0.17.5", optional = true }
base64 = { version = "0.13.0", optional = true }
wasm-bindgen = { version = "0.2.81", optional = true }
js-sys = { version = "0.3.58", optional = true }
transmute = "0.1.1"

[dev-dependencies]
devolve-ui-forms = { path = "../devolve-ui-forms" }
rand = "0.8.5"
test-log = "0.2.10"
env_logger = "0.9.0"
