[package]
name = "devolve-ui"
version = "0.1.0"
authors = ["jakobeha"]
description = "TUI (and planned future GUI) library using Reactive programming"
repository = "https://github.com/jakobeha/devolve-ui.rs"
license = "Apache-2.0"
keywords = ["ui", "tui", "terminal"]
categories = ["command-line-interface", "gui"]
edition = "2021"

[features]
# Include debug features by default
default = ["debug"]
time = ["tokio"]
tui = ["libc", "crossterm"]
debug = ["backtrace"]

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples=examples"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
devolve-ui-derive = { path = "../devolve-ui-derive" }
palette = "0.6"
replace_with = "0.1.7"
float-ord = "0.3.2"
tokio = { version = "1.18.2", features = ["rt", "time"], optional = true }
libc = { version = "0.2.126", optional = true }
crossterm = { version = "0.23.2", optional = true }
backtrace = { version = "0.3.65", optional = true }

[dev-dependencies]
test-log = "0.2.10"
env_logger = "0.9.0"