export * from 'core/vdom'
export * from 'core/hooks'
export * from 'core/platform'
export * from 'core/renderer'
export { setGlobalComponentOpts } from 'core/component'
export type { VComponent } from 'core/component'
export type { Lens } from 'core/lens'
